export const imgDescribe={
    picItem1:[
        "./IMG/item1/1.jpeg",
        "./IMG/item1/2.jpeg",
        "./IMG/item1/3.jpeg",
        "./IMG/item1/4.jpeg",
        "./IMG/item1/5.jpeg"
    ],
    picItem2:[
        "./IMG/item1/1.jpeg",
        "./IMG/item1/2.jpeg",
        "./IMG/item1/3.jpeg",
        "./IMG/item1/4.jpeg",
        "./IMG/item1/5.jpeg"
    ],
    picItem3:[
        "./IMG/item1/1.jpeg",
        "./IMG/item1/2.jpeg",
        "./IMG/item1/3.jpeg",
        "./IMG/item1/4.jpeg",
        "./IMG/item1/5.jpeg"
    ],
    picItem4:[
        "./IMG/item1/1.jpeg",
        "./IMG/item1/2.jpeg",
        "./IMG/item1/3.jpeg",
        "./IMG/item1/4.jpeg",
        "./IMG/item1/5.jpeg"
    ],
    picItem5:[
        "./IMG/item1/1.jpeg",
        "./IMG/item1/2.jpeg",
        "./IMG/item1/3.jpeg",
        "./IMG/item1/4.jpeg",
        "./IMG/item1/5.jpeg"
    ],
    picItem6:[
        "./IMG/item1/1.jpeg",
        "./IMG/item1/2.jpeg",
        "./IMG/item1/3.jpeg",
        "./IMG/item1/4.jpeg",
        "./IMG/item1/5.jpeg"
    ],
    picItem7:[
        "./IMG/item1/1.jpeg",
        "./IMG/item1/2.jpeg",
        "./IMG/item1/3.jpeg",
        "./IMG/item1/4.jpeg",
        "./IMG/item1/5.jpeg"
    ],
    picItem8:[
        "./IMG/item1/1.jpeg",
        "./IMG/item1/2.jpeg",
        "./IMG/item1/3.jpeg",
        "./IMG/item1/4.jpeg",
        "./IMG/item1/5.jpeg"
    ]
} 